INSERT INTO tb_genre (name) VALUES ('AÇÃO');
INSERT INTO tb_genre (name) VALUES ('AVENTURA');
INSERT INTO tb_genre (name) VALUES ('COMEDIA');
INSERT INTO tb_genre (name) VALUES ('ROMANCE');
INSERT INTO tb_genre (name) VALUES ('TERROR');
INSERT INTO tb_genre (name) VALUES ('FAMILA');
INSERT INTO tb_genre (name) VALUES ('FANTASIA');
INSERT INTO tb_genre (name) VALUES ('DRAMA');


INSERT INTO tb_movie (title, sub_Title, year, img_Uri, synopsis, genre_id) VALUES ('VELORES & FURIOSO: HOBBS & SHAW','Muita ação, adrenalina e pancadaria', 2019, 'https://www.themoviedb.org/t/p/original/uHGt74EYnrIusdpyhaOgQNwlqcp.jpg','Desde que se conheceram, em Velozes & Furiosos 7, Luke Hobbs (Dwayne Johnson) e Deckard Shaw (Jason Statham) constantemente bateram de frente, não só por inicialmente estarem em lados opostos mas, especialmente, pela personalidade de cada um. Agora, a dupla precisa unir forças para enfrentar Brixton (Idris Elba), um anarquista alterado geneticamente que se tornou uma ameaça biológica global. Para tanto, eles contam com a ajuda de Hattie (Vanessa Kirby), irmã de Shaw, que é também agente do MI6, o serviço secreto britânico.', 1);
INSERT INTO tb_movie (title, sub_Title, year, img_Uri, synopsis, genre_id) VALUES ('BUFFALO BOYS', ' ', 2018, 'https://www.themoviedb.org/t/p/original/tLKashUlRCN8zzYBXiago4eJPho.jpg','Traído pelas forças coloniais holandesas, Arana consegue escapar junto com seus sobrinhos Jamar e Suwo, os filhos recém-nascidos de Hamza, um dos últimos sultões indonésios lutando contra a tirania estrangeira. Em 1860, depois de vagar por anos nas planícies do Velho Oeste americano, Arana e os dois irmãos retornam à Indonésia para vingar seus entes queridos mortos e punir o homem mau que causou sua desgraça.', 1);
INSERT INTO tb_movie (title, sub_Title, year, img_Uri, synopsis, genre_id) VALUES ('24 HORAS PARA VIVER', 'Contratado para matar. Lutando para sobreviver.', 2017, 'https://www.themoviedb.org/t/p/original/7rbXlxr2JF09TilQagT4CikS8gF.jpg','Um assassino (Ethan Hawke) ganha uma segunda chance quando seu empregador o traz de volta à vida temporariamente, logo após ter sido morto no trabalho. Ele ganha então 24 horas para realizar sua missão e se redimir.', 1);
INSERT INTO tb_movie (title, sub_Title, year, img_Uri, synopsis, genre_id) VALUES ('MORTAL KOMBAT', 'Get over here.', 2021, 'https://www.themoviedb.org/t/p/original/hHF8FMuwUEkaklS7i3mpSBeSMOc.jpg','Nova aventura baseada no videogame Mortal Kombat. Na história, um jovem que nunca treinou artes marciais acaba envolvido em um gigantesco torneio de luta envolvendo guerreiros da Terra e lutadores e outras dimensões.', 1);
INSERT INTO tb_movie (title, sub_Title, year, img_Uri, synopsis, genre_id) VALUES ('12 HERÓIS', 'As forças especiais que fizeram história', 2018, 'https://www.themoviedb.org/t/p/original/yacDIqhY09hVME6yBgN0lBbBT8F.jpg','Após os atentados de 11 de setembro de 2001, o capitão Mitch Nelson (Chris Hemsworth) decide abandonar o posto de escritório recém-conquistado para retomar à ação. Ao lado de seu batalhão das Forças Especiais dos Estados Unidos, ele assume a responsabilidade de formar a primeira equipe a operar no Afeganistão após os ataques ao World Trade Center. Baseado em fatos reais.', 1);

INSERT INTO tb_movie (title, sub_Title, year, img_Uri, synopsis, genre_id) VALUES ('Bu y Bu', 'una aventura interdimensional', 2019, 'https://www.themoviedb.org/t/p/original/h3KCT6SZDc5R60vpQ6KBZALJHbM.jpg','Não temos uma sinopse em Português do Brasil. Você pode ajudar a ampliar o nosso banco de dados adicionando uma.', 2);
INSERT INTO tb_movie (title, sub_Title, year, img_Uri, synopsis, genre_id) VALUES ('Mortal Kombat', 'Get over here.',2021,'https://www.themoviedb.org/t/p/original/9yBVqNruk6Ykrwc32qrK2TIE5xw.jpg','Nova aventura baseada no videogame Mortal Kombat. Na história, um jovem que nunca treinou artes marciais acaba envolvido em um gigantesco torneio de luta envolvendo guerreiros da Terra e lutadores e outras dimensões.', 2);
INSERT INTO tb_movie (title, sub_Title, year, img_Uri, synopsis, genre_id) VALUES ('Godzilla vs. Kong', 'Um dos dois cairá',2021,'https://www.themoviedb.org/t/p/original/vpdBOYTWgjrh90JN1Yc1YnCPFkD.jpg','Em uma época em que os monstros andam na Terra, a luta da humanidade por seu futuro coloca Godzilla e Kong em rota de colisão que verá as duas forças mais poderosas da natureza no planeta se confrontarem em uma batalha espetacular para as idades. Enquanto Monarch embarca em uma missão perigosa em terreno desconhecido e descobre pistas sobre as origens dos Titãs, uma conspiração humana ameaça tirar as criaturas, boas e más, da face da terra para sempre.', 2);
INSERT INTO tb_movie (title, sub_Title, year, img_Uri, synopsis, genre_id) VALUES ('Mundo em Caos', 'Ninguém escapara do ruído',2021,'https://www.themoviedb.org/t/p/original/tW70HW4pUAia0RFASCTwEIgEuBc.jpg','Em um futuro não muito distante, em um mundo onde as mulheres desapareceram e os homens foram afetados pelo “ruído” – uma força que deixa seus pensamentos audíveis – Todd Hewitt encontra Viola, uma jovem misteriosa que aterrissou em seu planeta. Com Viola correndo perigo, Todd jura protegê-la e colocá-la fora de perigo. Para salvá-la, Todd terá que controlar seu “ruído”, descobrir sua própria força e desvendar todos os segredos sombrios que seu planeta e sua comunidade guardam.', 2);
INSERT INTO tb_movie (title, sub_Title, year, img_Uri, synopsis, genre_id) VALUES ('Esquadrão Trovão', 'Supernovatas quase heroínas.',2021,'https://www.themoviedb.org/t/p/original/iOwHLEGKTTwOQEbcQIuO8oLUlfJ.jpg','Duas amigas de infância se reencontram e acabam formando uma dupla de super-heroínas quando uma delas cria uma fórmula que dá superpoderes a pessoas comuns.', 2);

INSERT INTO tb_movie (title, sub_Title, year, img_Uri, synopsis, genre_id) VALUES ('Amor e Monstros','An apocalyptic love story.',2020,'https://www.themoviedb.org/t/p/original/sLSYI1B9IWo7MO8Q60v9JlOXyXn.jpg','Após o mundo ser invadido por monstros, Joel terá de se aventurar por metade do país, em meio a todo tipo de perigos, para tentar encontrar o amor da sua vida.',3);
INSERT INTO tb_movie (title, sub_Title, year, img_Uri, synopsis, genre_id) VALUES ('The Good Doctor: O Bom Doutor ','Sua mente é um mistério, seus métodos são um milagre.',2017,'https://www.themoviedb.org/t/p/original/6Ys6koNajP5ld9EIMfOSQrRquki.jpg','Um jovem médico com autismo começa a trabalhar em um famoso hospital. Além dos desafios da profissão, ele terá também que provar sua capacidade a seus colegas e superiores.',3);
INSERT INTO tb_movie (title, sub_Title, year, img_Uri, synopsis, genre_id) VALUES ('Pagando Bem, Que Mal Tem?','What would you do to get out of debt?',2007,'https://www.themoviedb.org/t/p/original/2nveqLXXVFB2ne4c9tLwZoLf5W9.jpg','Zack Brown (Seth Rogen) e Miriam Linky (Elizabeth Banks) são amigos há muito tempo, sendo que atualmente dividem uma casa e possuem diversas dívidas. Após terem a água e a luz cortadas, eles resolvem fazer um filme pornô caseiro para conseguir algum dinheiro. Desta forma selecionam alguns amigos para ajudá-los, jurando que o sexo não irá prejudicar a amizade existente. Só que, quando as gravações começam, o negócio se torna algo bem maior do que imaginavam.',3);
INSERT INTO tb_movie (title, sub_Title, year, img_Uri, synopsis, genre_id) VALUES ('O Virgem de 40 Anos','The longer you wait, the harder it gets.',2005,'https://www.themoviedb.org/t/p/original/lEmkmCoVH1WVATkqkmsHJpVrVVb.jpg','Andy Stitzer (Steve Carell) é um homem de 40 anos que possui um bom emprego, um apartamento próprio e mantém uma coleção de bonecos e revistas em quadrinhos. Porém, apesar da idade, Andy permanece virgem. Ele nem dá muita importância para isso, mas seus amigos não se conformam. Decididos a fazer com que Andy perca a virgindade, eles tentam fazer com que Trish (Catherine Keener), uma mãe solteira que também tem 40 anos, se torne sua parceira.',3);
INSERT INTO tb_movie (title, sub_Title, year, img_Uri, synopsis, genre_id) VALUES ('Ligeiramente Grávidos','Uma Confusão... Explosivamente Engraçado',2007,'https://www.themoviedb.org/t/p/original/cRDCtF0RM02LtciriXzHT2lDYrR.jpg','Alison Scott (Katherine Heigl) é uma jovem bonita e ambiciosa, que está para estrear como repórter de uma importante emissora de TV. Ben Stone (Seth Rogen) e seus 4 amigos dividem o aluguel de uma casa bagunçada, sendo que todos insistem em se manter na adolescência mesmo já tendo 20 e poucos anos. Alison e Ben se conhecem numa boate e, completamente bêbados, passam a noite juntos. A ligação entre eles terminaria aí, mas algumas semanas depois Alison liga para Ben para informá-lo que está esperando um filho dele. A notícia faz com que Ben passe a questionar sua própria vida, além de aproximar duas pessoas que preferiam jamais ter se conhecido.',3);

INSERT INTO tb_movie (title, sub_Title, year, img_Uri, synopsis, genre_id) VALUES ('Amor nas Alturas ','',2021,'https://www.themoviedb.org/t/p/original/lESgA6yI3fKV3tlwqeHKOu3Grdx.jpg','Quando o recém-viúvo Gavin e sua filha de nove anos, Parker, retornam à cidade natal dele, uma paixão por empinar pipas surge. A competição entre Gavin e a atual campeã Hannah esquenta, mas será que uma antiga conexão com a amiga de infância Katie vai ficar no caminho do amor de Gavin e Hannah? E Parker será feliz nesta nova comunidade?',4);
INSERT INTO tb_movie (title, sub_Title, year, img_Uri, synopsis, genre_id) VALUES ('Romance ','Love is desolate. Romance is temporary. Sex is forever.',1999,'https://www.themoviedb.org/t/p/original/3BAdo1f8JhTvXbP8AS5kgJubbxD.jpg','Although deeply in love with her boyfriend - and indeed sleeping in the same bed with him - a schoolteacher cannot handle the almost complete lack of intimacy he will allow. Increasingly frustrated, she gradually finds her sexual appetites leading her into ever more risky situations, including a developing one with the headmaster.',4);
INSERT INTO tb_movie (title, sub_Title, year, img_Uri, synopsis, genre_id) VALUES ('Crônicas Sexuais de uma Família Francesa','Uma historia de muito amor e briga',2021,'https://www.themoviedb.org/t/p/original/6V6y3aBbzO9fQDDjEPxtOI6vzBh.jpg','A celebração da sexualidade em três gerações. Geralmente, durante o jantar em família, fala-se sobre tudo, exceto sobre sexo. Essa rotina é perturbada quando o filho caçula, Romain, é pego se masturbando e filmando a cena com seu iPhone durante uma aula de biologia. Ele acaba sendo suspenso da escola. A partir de então, o sexo, que era um assunto tabu na casa, torna-se, subitamente, um tema de interesse real, levando os espectadores a se envolverem na vida íntima de cada pessoa da família: os pais, os filhos de 18, 20 e 22 anos e o avô.',4);
INSERT INTO tb_movie (title, sub_Title, year, img_Uri, synopsis, genre_id) VALUES ('Q Sexual Desire','Q Sexual Desire',2011,'https://www.themoviedb.org/t/p/original/kRQlMzD96FXxi6ByXKJXlEBUd9e.jpg','Num momento em que o país está com dificuldades , quando a sociedade está a lutar contra uma grande onda de desemprego. uma personagem, que simboliza o desejo, vai virar a vida de vários estrangeiros...',4);

INSERT INTO tb_movie (title, sub_Title, year, img_Uri, synopsis, genre_id) VALUES ('Invocação do Mal 3: A Ordem do Demônio','O caso demoníaco que chocou a América',2013,'https://www.themoviedb.org/t/p/original/nUMtHNnM4EWQ3Md4NfjJQBCvHos.jpg','Revela uma história arrepiante de terror, assassinato e um mal desconhecido que chocou até os investigadores paranormais da vida real, Ed e Lorraine Warren. Um dos casos mais intrigantes de seus arquivos, começa com uma luta pela alma de um garoto, depois os leva além de tudo o que já haviam visto antes, para marcar a primeira vez na história dos EUA um suspeito de assassinato alega possessão demoníaca como defesa.',5);
INSERT INTO tb_movie (title, sub_Title, year, img_Uri, synopsis, genre_id) VALUES ('Um Lugar Silencioso - Parte II ','Apenas o silêncio não será suficiente .',2021,'https://www.themoviedb.org/t/p/original/z2UtGA1WggESspi6KOXeo66lvLx.jpg','Logo após os acontecimentos mortais, até mesmo dentro de casa, a família Abbott precisa agora encarar o terror mundo afora, continuando a lutar para sobreviver em silêncio. Obrigados a se aventurar pelo desconhecido, eles rapidamente percebem que as criaturas que caçam pelo som não são as únicas ameaças que os observam pelo caminho de areia.',5);
INSERT INTO tb_movie (title, sub_Title, year, img_Uri, synopsis, genre_id) VALUES ('Espiral: O Legado de Jogos Mortais','',2021,'https://www.themoviedb.org/t/p/original/e17rqNSjdlpIYW4p31UXdC3ZyNu.jpg','Sob o comando do veterano da polícia Marcus, o detetive Ezekiel "Zeke" Banks se une ao seu parceiro novato Willem para desvendar uma série de assassinatos terríveis que estão acontecendo na cidade. Durante as investigações, Zeke acaba se envolvendo no mórbido jogo do assassino.',5);

INSERT INTO tb_movie (title, sub_Title, year, img_Uri, synopsis, genre_id) VALUES ('Eu Acredito','With God all things are possible',2017,'https://www.themoviedb.org/t/p/original/5Tw3Z9vcu1Hwo1CijEPineKPkFO.jpg','Brian Webber, de 9 anos de idade, tem um encontro sobrenatural com Deus, uma experiência que o leva à aventura das aventuras. Seus pais não estão muito felizes com isso, especialmente seu pai, Simon Webber, um apresentador de TV ateu. Felizmente, Brian encontra aliados no pastor de uma igreja local , e em um fuzileiro naval ferido dos EUA. A fé pura e inocente de Brian produz milagres extraordinários que rapidamente se tornam notícia na cidade.',5);
INSERT INTO tb_movie (title, sub_Title, year, img_Uri, synopsis, genre_id) VALUES ('Pets Monstruosos','',2021,'https://www.themoviedb.org/t/p/original/c7dFSqZQYqNNJVpacpIGZe3gkLW.jpg','Em Monster Pets (Monstros de Companhia), o cão Tinkles dá o seu melhor para arranjar um amigo',5);
INSERT INTO tb_movie (title, sub_Title, year, img_Uri, synopsis, genre_id) VALUES ('Soul ','Todos temos uma alma. Joe Gardner está prestes a descobrir a sua.',2020,'https://www.themoviedb.org/t/p/original/sS2V2AUpNygTV8aP2ux4ZDsx6PU.jpg','Joe Gardner é um professor de música de ensino fundamental desanimado por não conseguir alcançar seu sonho de tocar no lendário clube de jazz The Blue Note, em Nova York. Quando um acidente o transporta para fora do seu corpo, fazendo com que ele exista em outra realidade na forma de sua alma, ele se vê forçado a embarcar em uma aventura ao lado da alma de uma criança que ainda está aprendendo sobre si, para aprender o que é necessário para retomar sua vida.',5);
INSERT INTO tb_movie (title, sub_Title, year, img_Uri, synopsis, genre_id) VALUES ('Os Croods 2: Uma Nova Era','A sobrevivência que lute.',2020,'https://www.themoviedb.org/t/p/original/reDeoOvnih7Zv2xKXZAZL7w8KP6.jpg','Em Croods 2: Uma Nova Era, em busca de um habitat mais seguro, os Croods descobrem um paraíso que atende todas as suas necessidades. Entretanto, outras pessoas já moram neste lugar: Os Bettermans, uma família que se considera melhor e mais evoluída. À medida que as tensões entre os novos vizinhos começam a aumentar, uma nova ameaça impulsiona os dois clãs em uma aventura épica que os força abraçar suas diferenças, extrair forças um do outro e construir um futuro juntos.',5);

INSERT INTO tb_movie (title, sub_Title, year, img_Uri, synopsis, genre_id) VALUES ('Legados','Heróis. Vilões. Tanto faz.',2018,'https://www.themoviedb.org/t/p/original/wblSifvXAlqAYqEUoXmhpzeau7b.jpg','Hope Mikaelson, descendente da linhagem mais poderosa de vampiros, lobisomens e bruxas, frequenta a Escola Salvatore para Jovens e Superdotados, um refúgio onde ela pode aprender a controlar suas habilidades e impulsos sobrenaturais.',6);
INSERT INTO tb_movie (title, sub_Title, year, img_Uri, synopsis, genre_id) VALUES ('Charmed: Nova Geração','Mais fortes juntos.',2018,'https://www.themoviedb.org/t/p/original/lyY6FgSRXgkq2PP06mM92yQHgdS.jpg','Após a morte trágica de sua mãe, três irmãs que estão na faculdade descobrem que são bruxas. Rapidamente o trio precisa se unir para lutar as batalhas cotidianas e sobrenatural que todas as bruxas precisam encarar: desde acabar com demônios poderosos, até derrubar o patriarcado.',6);
INSERT INTO tb_movie (title, sub_Title, year, img_Uri, synopsis, genre_id) VALUES ('Os Originais','',2013,'https://www.themoviedb.org/t/p/original/dEI9IZEPcHXDiB4Yf3nYgXJtEOD.jpg','Klaus é um vampiro disposto a retomar Nova Orleans, cidade construída por sua família séculos atrás. Na missão, ele aprende mais sobre seu passado enquanto alianças são formadas.',7);
INSERT INTO tb_movie (title, sub_Title, year, img_Uri, synopsis, genre_id) VALUES ('Shadowhunters: Instrumentos Mortais','All the Legends Are True',2016,'https://www.themoviedb.org/t/p/original/p2kSeQt2qFMrGWg7Mj1woIZfTYP.jpg','A vida da jovem Clary Fray muda completamente quando ela descobre fazer parte de uma raça de humanos que caçam demônios e têm sangue de anjo.',7);


INSERT INTO tb_role( authority ) VALUES ('ROLE_VISITOR');
INSERT INTO tb_role( authority ) VALUES ('ROLE_MEMBER');


INSERT INTO tb_user (name, email, password) VALUES ('Bob Brown', 'bob@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (name, email, password) VALUES ('Ana Green', 'ana@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');


INSERT INTO tb_user_role (user_id, role_id) VALUES (1, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 2);

INSERT INTO tb_review (text, movie_id, user_id) VALUES ('esse filme é muito legal', 1,1);
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('nao gostei', 4,2);
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('sensacional', 10,1);
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('não tem muita ação', 20,2);
